# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 599ac23cc7bc3b8304133d918898f7f8ad1c84d471f3ec0271e6192706bff3259736a108e3cd6fe499755576ce1fc5d73f83958c46720ba0ed0bfbdf78d96e7b

test:
  secret_key_base: 6bb21c7986c5fe5ad837be9419ebc7b046ff9e42258d1916018541a7b5d1be9d5c7fc98434dd2230ee13c190ea4cee20289f23690347b7250e5a8a04a4d1aa5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
